CREATE DATABASE BANK;
USE BANK;
CREATE TABLE CUSTOMER(
ID INT PRIMARY KEY,
CUSTOMER_ID VARCHAR (20),
CUSTOMER_NAME VARCHAR (30),
BRANCH VARCHAR (15),
CITY VARCHAR (25),
PHONE VARCHAR (20)
);
CREATE TABLE ACCOUNT(
ID INT PRIMARY KEY,
ACCOUNT_ID VARCHAR(30),
CUSTOMER_ID VARCHAR (30),
 BALANCE VARCHAR (30)
);
CREATE TABLE ADMIN(
CUSTOMER_ID VARCHAR (25),
PASSWORD VARCHAR (20)
);
INSERT INTO ADMIN VALUES
("ADMINS1","13257"),
("ADMINS2","76321");
SELECT * FROM ADMIN;